const C=window.CODE_DIRECTORY||[];const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const KEY='promptos_state_v2';let saved=JSON.parse(localStorage.getItem(KEY)||'{}');
const state={query:'',category:'All',sort:'number',page:1,perPage:18,view:'grid',favorites:new Set(saved.favorites||[]),recent:saved.recent||[],stack:[],currentView:'dashboard'};
const cats=[...new Set(C.map(x=>x.category))];const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function persist(){localStorage.setItem(KEY,JSON.stringify({favorites:[...state.favorites],recent:state.recent}))}function toast(m){let t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),1500)}
function copy(text){navigator.clipboard?.writeText(text);toast(text+' copied');}function use(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,20);persist()}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);persist();updateCounts();renderAll();toast(state.favorites.has(id)?'Added to favorites':'Removed from favorites')}
function filtered(){let a=C.filter(x=>state.category==='All'||x.category===state.category);let q=state.query.trim().toLowerCase();if(q)a=a.filter(x=>(x.code+' '+x.purpose+' '+x.category).toLowerCase().includes(q));if(state.currentView==='favorites')a=a.filter(x=>state.favorites.has(x.id));if(state.sort==='alpha')a.sort((a,b)=>a.code.localeCompare(b.code));else if(state.sort==='purpose')a.sort((a,b)=>a.purpose.localeCompare(b.purpose));else a.sort((a,b)=>a.id-b.id);return a}
function card(x){let fav=state.favorites.has(x.id);return `<article class="command-card"><div class="command-top"><span class="command-num">#${String(x.id).padStart(3,'0')}</span><span class="badge">${esc(x.category)}</span></div><button class="fav ${fav?'on':''}" onclick="toggleFav(${x.id})">${fav?'★':'☆'}</button><code>${esc(x.code)}</code><p>${esc(x.purpose)}</p><div class="card-actions"><button class="btn primary" onclick="copyAndUse('${esc(x.code)}',${x.id})">Copy</button><button class="btn" onclick="details(${x.id})">Details</button><button class="btn" onclick="addStack(${x.id})">＋ Stack</button></div></article>`}
function copyAndUse(code,id){use(id);copy(code)}function details(id){let x=C.find(v=>v.id===id);if(!x)return;use(id);$('#modalBody').innerHTML=`<span class="eyebrow">${esc(x.category)} · #${String(x.id).padStart(3,'0')}</span><h2>${esc(x.code)}</h2><p>${esc(x.purpose)}</p><div class="card-actions"><button class="btn primary" onclick="copyAndUse('${esc(x.code)}',${x.id});closeModal()">Copy command</button><button class="btn" onclick="toggleFav(${x.id});closeModal()">${state.favorites.has(id)?'Remove favorite':'Save favorite'}</button><button class="btn" onclick="addStack(${id});closeModal()">Add to stack</button></div>`;$('#modal').classList.add('open');persist();updateCounts()}
function closeModal(){$('#modal').classList.remove('open')}
function updateCounts(){$('#total').textContent=C.length;$('#categories').textContent=cats.length;$('#favorites').textContent=state.favorites.size;$('#recentCount').textContent=state.recent.length;$('#sideFav').textContent=state.favorites.size}
function renderCats(){let counts={};C.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);$('#categoryGrid').innerHTML=cats.slice(0,10).map(c=>catCard(c,counts[c])).join('');$('#allCategories').innerHTML=cats.map(c=>catCard(c,counts[c],true)).join('')}
function catCard(c,n,large=false){return `<button class="category-card" onclick="openCategory('${esc(c)}')"><span class="cat-symbol">◈</span><strong>${esc(c)}</strong><small>${n} command${n===1?'':'s'}</small></button>`}
function openCategory(c){state.category=c;state.query='';state.page=1;showView('commands');$('#category').value=c;renderCommands()}
function renderFocus(){let x=C[(new Date().getDate()*7)%C.length];$('#focusCommand').innerHTML=`<span class="focus-category">${esc(x.category)}</span><div class="focus-code">${esc(x.code)}</div><div class="focus-purpose">${esc(x.purpose)}</div>`;$('#focusCopy').onclick=()=>copyAndUse(x.code,x.id);$('#focusStar').textContent=state.favorites.has(x.id)?'★':'☆';$('#focusStar').onclick=()=>toggleFav(x.id)}
function renderPopular(){let ids=[1,2,3,16].filter(i=>C.some(x=>x.id===i));$('#popular').innerHTML=ids.map(i=>{let x=C.find(v=>v.id===i);return `<div class="mini-command"><code>${esc(x.code)}</code><p>${esc(x.purpose)}</p><button class="btn small" onclick="copyAndUse('${esc(x.code)}',${x.id})">Copy</button></div>`}).join('')}
function renderCommands(){let a=filtered(),pages=Math.max(1,Math.ceil(a.length/state.perPage));if(state.page>pages)state.page=pages;let start=(state.page-1)*state.perPage,show=a.slice(start,start+state.perPage);$('#grid').innerHTML=show.length?show.map(card).join(''):'<div class="empty">No matching commands. Try a different search or reset the filters.</div>';$('#resultCount').textContent=`Showing ${a.length?start+1:0}–${Math.min(start+state.perPage,a.length)} of ${a.length}`;$('#page').textContent=`${state.page} / ${pages}`;$('#prev').disabled=state.page<=1;$('#next').disabled=state.page>=pages;document.body.classList.toggle('list-mode',state.view==='list')}
function renderSpecial(id,arr){$('#'+id).innerHTML=arr.length?arr.map(x=>card(x)).join(''):'<div class="empty">Nothing here yet.</div>'}
function renderBuilder(){let q=($('#builderSearch')?.value||'').toLowerCase();let pool=C.filter(x=>(x.code+' '+x.purpose).toLowerCase().includes(q)&&!state.stack.includes(x.id)).slice(0,20);$('#builderResults').innerHTML=pool.map(x=>`<button class="builder-item" onclick="addStack(${x.id})"><code>${esc(x.code)}</code><small>${esc(x.purpose)}</small></button>`).join('');$('#stackCount').textContent=state.stack.length+' / 6';$('#stack').innerHTML=state.stack.map((id,i)=>{let x=C.find(v=>v.id===id);return `<span class="stack-chip">${esc(x.code)} <button onclick="removeStack(${i})">×</button></span>`}).join('');let text=state.stack.map(id=>C.find(v=>v.id===id)?.code).filter(Boolean).join(' ');$('#promptPreview').textContent=text||'Add commands from the left to start building.'}
function addStack(id){if(state.stack.length>=6){toast('Stack limit is 6');return}if(!state.stack.includes(id))state.stack.push(id);use(id);renderBuilder();toast('Added to prompt stack')}
function removeStack(i){state.stack.splice(i,1);renderBuilder()}function showView(v){state.currentView=v;$$('.view').forEach(x=>x.classList.remove('active-view'));$('#'+v).classList.add('active-view');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#pageTitle').textContent={dashboard:'Command Dashboard',commands:'All Visual Commands',favorites:'Saved Commands',categories:'Capability Categories',builder:'Prompt Builder',recent:'Recently Used',about:'About the Codebook'}[v];$('#crumb').textContent=v.toUpperCase();if(v==='favorites')renderSpecial('favGrid',C.filter(x=>state.favorites.has(x.id)));if(v==='recent')renderSpecial('recentGrid',state.recent.map(id=>C.find(x=>x.id===id)).filter(Boolean));if(v==='builder')renderBuilder();window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){updateCounts();renderCats();renderFocus();renderPopular();if(state.currentView==='commands')renderCommands();if(state.currentView==='favorites')renderSpecial('favGrid',C.filter(x=>state.favorites.has(x.id)));if(state.currentView==='recent')renderSpecial('recentGrid',state.recent.map(id=>C.find(x=>x.id===id)).filter(Boolean));renderBuilder()}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#category').innerHTML='<option value="All">All categories</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
$('#search').oninput=e=>{state.query=e.target.value;state.page=1;renderCommands()};$('#globalSearch').oninput=e=>{state.query=e.target.value;state.page=1;showView('commands');$('#search').value=e.target.value;renderCommands()};$('#category').onchange=e=>{state.category=e.target.value;state.page=1;renderCommands()};$('#sort').onchange=e=>{state.sort=e.target.value;state.page=1;renderCommands()};$('#prev').onclick=()=>{state.page--;renderCommands()};$('#next').onclick=()=>{state.page++;renderCommands()};$('#gridBtn').onclick=()=>{state.view='grid';$('#gridBtn').classList.add('active');$('#listBtn').classList.remove('active');renderCommands()};$('#listBtn').onclick=()=>{state.view='list';$('#listBtn').classList.add('active');$('#gridBtn').classList.remove('active');renderCommands()};$('#clear').onclick=()=>{$('#search').value='';$('#globalSearch').value='';state.query='';state.category='All';$('#category').value='All';state.page=1;renderCommands()};$('#random').onclick=()=>details(C[Math.floor(Math.random()*C.length)].id);$('#random2').onclick=()=>details(C[Math.floor(Math.random()*C.length)].id);$('#export').onclick=()=>exportFav();$('#export2').onclick=()=>exportFav();function exportFav(){let a=C.filter(x=>state.favorites.has(x.id));let blob=new Blob([JSON.stringify(a,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),ael=document.createElement('a');ael.href=u;ael.download='promptos-favorites.json';ael.click();URL.revokeObjectURL(u)}$('#builderSearch').oninput=renderBuilder;$('#copyStack').onclick=()=>{let t=state.stack.map(id=>C.find(x=>x.id===id)?.code).filter(Boolean).join(' ');if(t)copy(t);else toast('Add commands first')};$('#clearStack').onclick=()=>{state.stack=[];renderBuilder()};$('#close').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape')closeModal()});
renderAll();

/* Theme + domain integration */
(function(){
  const THEME_KEY='promptos_theme';
  const btn=document.getElementById('themeToggle');
  const meta=document.getElementById('themeColor');
  function systemTheme(){return matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'}
  function applyTheme(theme){
    if(theme==='system') document.body.removeAttribute('data-theme');
    else document.body.setAttribute('data-theme',theme);
    const dark=(theme==='dark')||(theme==='system'&&systemTheme()==='dark');
    if(btn){btn.textContent=dark?'☀':'☾';btn.title=dark?'Switch to light theme':'Switch to dark theme'}
    if(meta)meta.content=dark?'#07090e':'#f6f7fb';
  }
  const savedTheme=localStorage.getItem(THEME_KEY)||'system'; applyTheme(savedTheme);
  btn?.addEventListener('click',()=>{const current=document.body.getAttribute('data-theme')||systemTheme();const next=current==='dark'?'light':'dark';localStorage.setItem(THEME_KEY,next);applyTheme(next);toast(next==='dark'?'Dark theme enabled':'Light theme enabled')});
  matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((localStorage.getItem(THEME_KEY)||'system')==='system')applyTheme('system')});
  if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
